### ISSUE TITLE
Not working on jupyter notebook

### ISSUE THREAD

**Issue by yanaiela** [TeamHG-Memex/tensorboard_logger#17]
any idea why? or how to fix?
on standard python interpreter on the same machine it works perfectly

**Comment by lopuhin** [comment]
@yanaiela could you please give more details, what do you see - is there a traceback, or it's not logging silently, or it's logging what you expect?

**Comment by yanaiela** [comment]
@lopuhin thanks for answering.
The thing is, that nothing appears. The tensor board seems to no have gotten the data. Also when running with the python standard interpreter, a folder is created with a log file. When running with jupyter no such folder appear to be created

**Comment by lopuhin** [comment]
@yanaiela thank for details, I'll try to check it out. Could be either related to auto-reload, if you have it enabled, or with a different current directory. If you have time, could you also try:
- passing absolute path to ``configure``
- if you have code auto-reload enabled, maybe try using ``tensorboard_logger.Logger`` object and using it's ``configure`` and ``log_value`` methods instead of ``tensorboard_logger.configure`` and ``tensorboard_logger.log_value``

**Comment by yanaiela** [comment]
Passing an absolute path through the configure function worked! 
thanks
